### ISSUE TITLE
1.18.1 Server Crash

### ISSUE THREAD

**Issue by Tyrius1** [Patrigan/FactionCraft#11]
Getting a server crash. Can't reproduce doing anything specifically it just seems sort of random.
MC 1.18.1
Forge 39.0.59
FactionCraft 1.0.4
https://pastebin.com/nQJhhU9Q

**Comment by Patrigan** [comment]
Discovered where the issue is coming from. Will be releasing a fix soon.
In short, boosts were trying to apply to Patrols even when the patrol itself didn't actually spawn an entity.

**Comment by Patrigan** [comment]
1.0.5 released today fixes this.
