### ISSUE TITLE
1.18.1 Crash

### ISSUE THREAD

**Issue by CapitaineYolo** [Patrigan/FactionCraft#12]
The game crashed while I was riding a donkey in the middle of nowhere.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 02.02.22, 18:29
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "com.patrigan.faction_craft.capabilities.factionentity.FactionEntity.getFaction()" because the return value of "com.patrigan.faction_craft.capabilities.factionentity.FactionEntityHelper.getFactionEntityCapability(net.minecraft.world.entity.Mob)" is null
	at com.patrigan.faction_craft.raid.target.FactionBattleRaidTarget.lambda$checkLossCondition$0(FactionBattleRaidTarget.java:78) ~[faction_craft-1.18.1-1.0.4.jar%2369!/:1.18.1-1.0.4] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at com.patrigan.faction_craft.raid.target.FactionBattleRaidTarget.checkLossCondition(FactionBattleRaidTarget.java:78) ~[faction_craft-1.18.1-1.0.4.jar%2369!/:1.18.1-1.0.4] {re:classloading}
	at com.patrigan.faction_craft.raid.Raid.tick(Raid.java:175) ~[faction_craft-1.18.1-1.0.4.jar%2369!/:1.18.1-1.0.4] {re:classloading}
	at com.patrigan.faction_craft.capabilities.raidmanager.RaidManager.tick(RaidManager.java:50) ~[faction_craft-1.18.1-1.0.4.jar%2369!/:1.18.1-1.0.4] {re:classloading}
	at com.patrigan.faction_craft.raid.RaidEvents.onWorldTickEvent(RaidEvents.java:18) ~[faction_craft-1.18.1-1.0.4.jar%2369!/:1.18.1-1.0.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_18_RaidEvents_onWorldTickEvent_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.64-universal.jar%2390!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:874) ~[client-1.18.1-20211210.034407-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2386!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2386!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 774822384 bytes (738 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1b82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24413,16
	Virtual memory used (MB): 21500,06
	Swap memory total (MB): 8115,57
	Swap memory used (MB): 262,54
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['CapitaineYolo'/68604, l='ServerLevel[Survival]', x=-527.85, y=65.79, z=1615.24]]
	Data Packs: vanilla, mod:beaconsforall, mod:seedfix, mod:effective_fg, mod:physicsmod (incompatible), mod:guardvillagers (incompatible), mod:unlitcampfire, mod:nullscape_forge, mod:forge, mod:flywheel, mod:create, mod:seedfix_forge, mod:geckolib3 (incompatible), mod:creeperoverhaul, mod:fallingleaves (incompatible), mod:hardcore_torches, mod:clumps (incompatible), mod:explosiont (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:villagespawnpoint, mod:collective, mod:shutupexperimentalsettings (incompatible), mod:faction_craft (incompatible), mod:crafttweaker (incompatible), mod:happytrails (incompatible), mod:cloth_config (incompatible), mod:sound_physics_remastered, mod:copperarmorandtools, mod:autoplant (incompatible), mod:keepmysoiltilled, mod:strongfarmland (incompatible), mod:nametagtweaks, mod:craftablehorsearmour
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.3.3.zip
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Amplified+Nether+1.0.1+_+Forge.jar                |Amplified Nether + Seed Fix   |seedfix                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		physics-mod-2.6.6-mc-1.18-forge.jar               |Physics Mod                   |physicsmod                    |2.6.6               |DONE      |Manifest: NOSIGNATURE
		villagespawnpoint_1.18.1-1.9.jar                  |Village Spawn Point           |villagespawnpoint             |1.9                 |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.18.1-1.3.1.jar                    |Falling Leaves                |fallingleaves                 |1.3.1               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		hardcore_torches-1.2.2.jar                        |Hardcore Torches              |hardcore_torches              |1.2.2               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.4-1.18+.jar        |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Explosiont-1.18-2.5.jar                           |Explosion't                   |explosiont                    |1.18-2.5            |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.16.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.16.0              |DONE      |Manifest: NOSIGNATURE
		faction_craft-1.18.1-1.0.4.jar                    |Faction Craft                 |faction_craft                 |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		beaconsforall-forge-1.18.1-5.2.0.0.jar            |Beacons For All               |beaconsforall                 |1.18.1-5.2.0.0      |DONE      |Manifest: NOSIGNATURE
		effective_for_forge-1.001.jar                     |Effective (Forge)             |effective_fg                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		copper-mod-1.9.jar                                |Copper Armor & Tools          |copperarmorandtools           |1.9                 |DONE      |Manifest: NOSIGNATURE
		HappyTrails-1.18.1-1.39.0.8.jar                   |Happy Trails Mod              |happytrails                   |1.18.1-1.39.0.8     |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.1.4.0.jar                     |Guard Villagers               |guardvillagers                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		unlitcampfire-forge-1.18-1.4.0.0.jar              |Unlit Campfire                |unlitcampfire                 |1.18-1.4.0.0        |DONE      |Manifest: NOSIGNATURE
		nametagtweaks_1.18.1-1.8.jar                      |Name Tag Tweaks               |nametagtweaks                 |1.8                 |DONE      |Manifest: NOSIGNATURE
		autoplant-1.18-0.1.0.jar                          |autoplant                     |autoplant                     |1.18-0.1.0          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		keepmysoiltilled_1.18.1-1.1.jar                   |Keep My Soil Tilled           |keepmysoiltilled              |1.1                 |DONE      |Manifest: NOSIGNATURE
		Nullscape_v1.1_Fabric+Forge.jar                   |Seed Fix + Nullscape          |nullscape_forge               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.1-9.0.45.jar              |CraftTweaker                  |crafttweaker                  |9.0.45              |DONE      |Manifest: NOSIGNATURE
		Craftable+Horse+Armour++Saddle-1.18-1.8-Forge.jar |CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.8                 |DONE      |Manifest: NOSIGNATURE
		strongfarmland-1.18-1.1.0.jar                     |Stronger Farmland             |strongfarmland                |1.18-1.1.0          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.1-1.0.4.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.64-universal.jar                |Forge                         |forge                         |39.0.64             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Terralith_v2.0.12_Fabric+Forge.jar                |Seed Fix + Terralith          |seedfix_forge                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.10.jar                    |GeckoLib                      |geckolib3                     |3.0.10              |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-1.18.1-0.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |0.3.0               |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: Off
	Crash Report UUID: ec3bd15d-12b3-4a80-b0f8-b952270343ff
	FML: 39.0
	Forge: net.minecraftforge:39.0.64

**Comment by Patrigan** [comment]
I wonder how this one is even possible xD
I will foresee a catch for it, so it doesn't crash anymore. But I might need a better solution in the long run.

**Comment by Patrigan** [comment]
1.0.5 released today fixes this
