### ISSUE TITLE
I tried to use it on the server, but it crashed halfway through startup

### ISSUE THREAD

**Issue by mcmso** [Patrigan/FactionCraft#19]
faction_craft-1.16.5-1.1.1.jar   dungeons_libraries-1.16.5-0.0.9-beta.jar   dungeons_mobs-1.16.5-2.0.3-beta.jar            https://paste.ubuntu.com/p/MVtHTJXjjm/
If you need more information, please contact me and I will do my best to provide it

**Comment by Patrigan** [comment]
This mixin has been rewritten recently. Should no longer cause this.

Can you confirm?

**Comment by Patrigan** [comment]
Closing as should be fixed.
