### ISSUE TITLE
minimum and maximum ranks ignored in all types of raids, suspicion of weight being ignored in faction battles

### ISSUE THREAD

**Issue by TruffleHistorian** [Patrigan/FactionCraft#22]
multiple entities spawn in the same wave or factionbattle even though their minimum and maximum rank is leader (thus there should only be one per wave), too many entities with low weight spawning consistantly in faction battles

used factioncraft version :  faction_craft-1.18.2-1.1.3.jar

**Comment by Patrigan** [comment]
Workaround with min and max per wave. Ranks are temporarily suspended for a different implementation.
