### ISSUE TITLE
1.19.2 Crash

### ISSUE THREAD

**Issue by XxMasterepicxX0** [Patrigan/FactionCraft#29]
When I load into the world, the mod crash. Here is the crash report.

[crash-2023-02-13_17.39.16-client.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/10726917/crash-2023-02-13_17.39.16-client.txt)

**Comment by Patrigan** [comment]
Fixed in upcoming FactionCraft 1.19.2-1.2.0
