### ISSUE TITLE
Crash 1.18.2

### ISSUE THREAD

**Issue by Rostas** [Patrigan/FactionCraft#30]
Minecraft version: 1.18.2
Forge: 40.2.0
Mod version: faction_craft-1.18.2-1.1.6.jar

Seems to happen when any faction spawns as well as spawning by commands

[crash-2023-02-14_00.21.47-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/10729031/crash-2023-02-14_00.21.47-server.txt)

**Comment by Patrigan** [comment]
Fixed in 1.1.8
