### ISSUE TITLE
1.19.2 Forge Dedicated Server Crash 

### ISSUE THREAD

**Issue by PhoenixEpic** [Patrigan/FactionCraft#31]
Server crashed during play, forcing disconnect from all players connected. Issue appears to stem from loading a patrol. Server is functioning without crashes with mod removed. Fresh world and server file. 

All mods updated to current released versions, forge server and clients on released stable version 43.2.0

[crash-2023-02-21_21.37.06-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/10807461/crash-2023-02-21_21.37.06-server.txt)

**Comment by manue777-droid** [comment]
the same with version 1.18.2

**Comment by Patrigan** [comment]
Fixed for 1.19.2. To be fixed for 1.18.2. Please track #39 for updates on the backport.
