### ISSUE TITLE
Client Crash Starting New World

### ISSUE THREAD

**Issue by Cixon** [Patrigan/FactionCraft#32]
**Issue:**
Cannot invoke "com.patrigan.faction_craft.capabilities.raidmanager.RaidManager.tick()" because "raidManagerCapability" is null

**Crash:**
[crash-2023-03-01_08.25.30-client.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/10861988/crash-2023-03-01_08.25.30-client.txt)

**Log (line 22,834):**
[latest.log](https://github.com/Infamous-Misadventures/FactionCraft/files/10861995/latest.log)

FML: 40.2.1
MCV: 1.18.2
Version: v1.1.7

**Comment by Patrigan** [comment]
Fixed in 1.1.8
