### ISSUE TITLE
[1.18.2] Singleplayer crash while exploring DarkForest.

### ISSUE THREAD

**Issue by Cixon** [Patrigan/FactionCraft#39]
### Line 20,619
[latest.log](https://github.com/Infamous-Misadventures/FactionCraft/files/11523936/latest.log)

Pls fix.. thank you

**Comment by Cixon** [comment]
[crash-2023-05-21_02.43.47-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/11523949/crash-2023-05-21_02.43.47-server.txt)

crash if you need it

**Comment by Cixon** [comment]
Occurred again in a plains biome.

[crash-2023-05-26_23.06.16-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/11580960/crash-2023-05-26_23.06.16-server.txt)

**log (7,576):**
[latest.log](https://github.com/Infamous-Misadventures/FactionCraft/files/11580962/latest.log)

**Comment by Patrigan** [comment]
Needs the AddAllowedRanks bugfix backported.

**Comment by Patrigan** [comment]
Fixed in 1.18.2-1.1.9
