### ISSUE TITLE
Crash when a faction battle started up.

### ISSUE THREAD

**Issue by Darkmega18** [Patrigan/FactionCraft#40]
[crash-2023-07-08_00.36.33-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/11983745/crash-2023-07-08_00.36.33-server.txt)

1.19.2 Minecraft and forge 43.2.14
faction craft 1.3.4.

Posting it here so it's logged and not forgotten in a discord chat somewhere.

I was testing some mods out in some ice plains. Game comes to a halt when a faction battle spawns nearby. Thats about all. it was default settings, plus whatever other mods I have.

Something about a digger and some entity type returning null. big oof.

**Comment by Patrigan** [comment]
Fixed in 1.3.5
