### ISSUE TITLE
Possible bad interaction with neutral mobs from different mods(tested with Alex Mobs and Better Animal Plus)

### ISSUE THREAD

**Issue by SkullNo1se** [Patrigan/FactionCraft#41]
Hi,i'm here to report this:
While Factioncraft it's loaded into the world,any kind of harming interactions against any kind of mob(as Pacific,Neutral or Aggressive),will trigger all the neutral mobs that are nearby to gang you up (some Alex mobs are neutral,and i was swarmed by them while defending myself from a zombie in a Savannah),out of curiosity,i tried mobs from other mods and did it with Better Animal Plus animals,and got the same interaction.
If you need more info,just text me there and i'll see if i can provide more data.
Forge version: 43.2.19
Minecraft version 1.19.2
Factioncraft version: 1.3.4
Alex Mobs version: 1.21.1
Better Animal Plus version: 11.0.10

Thank for your time,
SkullNoise.

**Comment by Darkmega18** [comment]
AAaAAaaAAaaAaaah.

**Comment by SkullNo1se** [comment]
hi dark,seems you like to invade others issues report,pal.

**Comment by Darkmega18** [comment]
our issue report. _[insert communist bugs bunny here]_

cause I have this issue too. so I'll give it a poke.

**Comment by Patrigan** [comment]
Should be fixed in upcoming 1.3.5
