### ISSUE TITLE
Crash Factioncraft - 1.18.2

### ISSUE THREAD

**Issue by Aarods** [Patrigan/FactionCraft#43]
[crash-2023-08-10_23.24.44-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/12317736/crash-2023-08-10_23.24.44-server.txt)

Notes:
When playing on the server in full raid on server side the server closes with a crash report.

Conditions:
When you try to do a raid with a lot of mobs (values = 90+)
This error is more common in the wave 3.

Version:
faction_craft-1.18.2-1.1.10

**Comment by codexyster** [comment]
Got similar situation. A raid happened, and when the bar reached full the game crashed. Also 1.18.2-1.1.10.
[crash-2023-09-04_21.55.19-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/12514419/crash-2023-09-04_21.55.19-server.txt)

**Comment by wabeb325** [comment]
Same here, is impossible to play more than 3 waves with this error. :(
[crash-2023-09-07_00.06.31-server.txt](https://github.com/Infamous-Misadventures/FactionCraft/files/12549936/crash-2023-09-07_00.06.31-server.txt)

**Comment by sentwayfarer** [comment]
Any updates on this? I've got the same crash.

**Comment by Patrigan** [comment]
Bug Identified. Fix coming soon.

**Comment by Patrigan** [comment]
Fixed and released in 1.10.11
