### ISSUE TITLE
[1.16.5] Crash "com.patrigan.faction_craft.faction.FactionEvents.onLivingHurtEvent(FactionEvents.java:22)"

### ISSUE THREAD

**Issue by SkullDiamond** [Patrigan/FactionCraft#5]
**Bug description**
Using better weather and starting to acid rain the game crashed 

**Steps to reproduce** 
1. New game
2. Use /betterweather setweather betterweather-acid_rain_thundering

**Crash log**
https://pastebin.com/s4Tpncme

**Comment by Patrigan** [comment]
Should be resolved with a work around in 1.0.2. Released now on CF!
