### ISSUE TITLE
[1.16.5] Game Crashes on startup

### ISSUE THREAD

**Issue by SkullDiamond** [Patrigan/FactionCraft#8]
**Bug description**
I tried to use the last update (faction_craft-1.16.5-1.0.3.jar)

**Crash log**
I dont have a crash log just the latest.log

https://pastebin.com/mbESANtH

**Comment by Patrigan** [comment]
Yup, something weird and funky going on. Works on my local environment, but once loaded through CF it crashes. Facepalm.

I'll fix and bring it back, for now use 1.0.2 (1.0.3 has been removed from CF completely)

Apologies for the inconvenience.

**Comment by Patrigan** [comment]
Fixed in 1.0.4.
